### PR TITLE
[#32][#61] added vsdbg to launch.json, added rsa-sha2-256 for ssh.net…

### PR DESCRIPTION
**Pull request by zeusware**
Related: #32 #61
* Added `vsdbg` to `launch.json`, added rsa-sha2-256 for ssh.net, added ssh.exe adapter, working version

## New Features

1. Ubuntu 22.04 LTS OpenSSH package does not support the ssh algo: ssh-rsa u intended bei generating via '**ssh-keygen -m PEM -t rsa -b 4096**' by  default anymore, 
Adding the RSA-SHA2-256 for SSH.Net for interpreting private keys made by   **ssh-keygen -m PEM -t rsa -b 4096** allowing connecting directly.
2. vsdbg was missing in launch.json, this has been merged already
3. Using a ppk via plink is obsolete if u gen the key via PowerShell `ssh-keygen`, so u have now the option to use the system integrated ssh.exe (PS 6 integrate that by default)

### CODE REVIEW

**Comment by DamianSuess** [comment]
Thanks, @zeusware!

While this PR will be reviewed and tested this week. Do you mind updating the description to clearly read the PR's intent and what it addresses? This helps keep the history system clear and tidy for future PR readers.

**Comment by zeusware** [comment]
1)
Ubuntu 22.04 LTS OpenSSH package does not supports the ssh algo: ssh-rsa u intended bei generating via '**ssh-keygen -m PEM -t rsa -b 4096**' by  default anymore, 
Adding the rsa-sha2-256 for SSH.Net for interpreting private keys made by   **ssh-keygen -m PEM -t rsa -b 4096** allowing connecting directly.
2) vsdbg was missing in launch.json, this has been merged already
3) using a ppk via plink is obsolete if u gen the key via PowerShell ssh-keygen, so u have now the option  to use the system integrated ssh.exe (PS 6 integrate that by default)

**Comment by DamianSuess** [comment]
Amazing contribution @zeusware!!
I'm going to update the release notes with credit given to you on the new addition and publish the package. Would you like me to use a formal name, or "ZeusWare"?

**Comment by zeusware** [comment]
Thx ;)
I've some more in Pipe if u like.
Please use "ZeuSWarE GmbH" ,...
with best regards

**Pull request merged**
