### PR TITLE
Fix connection error when using SSH private key. Fixes #82.

### LINKED ISSUE #82: SSH Connection error since update 2.2.0
## Description
Since the last extension update I cannot use the extension anymore. The code builds fine, but then I get the following error while connecting through SSH:

```
08:37:50.349: Build was successful
08:37:50.371: SSH configuring private key connection...
08:37:50.401: SSH connecting...
08:37:52.091: An error occurred during the build process. La valeur ne peut pas être null.
Nom du paramètre : connectionInfo
08:37:52.091: Failed to perform actions.
```
I updated Visual Studio to the latest version, but it did not help.

## Severity (1-5)
4: Unusable extension, but no crash.

## Steps To Reproduce
1. Click on "Build and Deploy" in the Linux Debugger extension drop-down menu.

## Expected Behavior
SSH upload working as before.

## Configuration:
* **Local OS:** Windows 10 22H2 Build19045.4170
* **Visual Studio:** 2022 64bits Version 17.9.3
* **VS Linux Debugger:** Version 2.2.0
* **Remote OS:** Raspberry Pi 4 with Raspberry Pi OS Lite (64-bit). All packages updated.

## Additional Context
It was working fine two weeks ago. I did not use Visual Studio since.
I am using an SSH key file as credentials (username/password not allowed).
I can connect to my remote device using Putty or powershell with the same SSH key file.

### PR DESCRIPTION
**Pull request by jarnokamminga**
Connection info wasn't properly updated (read; kept in sync).

### CODE REVIEW

**Comment by DamianSuess** [comment]
Thank you for the catch. I'll get it on the test bench this week

**Comment by jarnokamminga** [comment]
> Thank you for the catch. I'll get it on the test bench this week

You're wellcome. The patch supplied in the thread of #82 was only partially the issue. I only made the changes that were causing the connection problems. With this fix I am able to connect using a private key (RSA/4096) to my Linux Server's. Unlike before the change. Beforehand it wasn't useable with a private key at all.

Good luck testing it.

**Review by 5andr0 — APPROVED** [review]
Thanks for the fix. Works for me

**Comment by jarnokamminga** [comment]
> Thanks for the fix. Works for me

You're welcome! Glad to see it has been merged.

**Pull request merged**
